# Generated by Django 5.2.8 on 2025-11-29 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: T3 Centre Ville - Résidence Mada', max_length=200)),
                ('type_bien', models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('MAISON', 'Maison'), ('COMMERCE', 'Local Commercial'), ('TERRAIN', 'Terrain')], default='APPARTEMENT', max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(default='Dakar', max_length=100)),
                ('surface', models.PositiveIntegerField(help_text='En m²')),
                ('nb_pieces', models.PositiveIntegerField(default=1, verbose_name='Nombre de pièces')),
                ('description', models.TextField(blank=True)),
                ('loyer_ref', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Loyer de référence (FCFA/Ar)')),
                ('charges_ref', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Charges estimées')),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='biens/')),
                ('est_actif', models.BooleanField(default=True, help_text='Décochez si le bien est vendu ou retiré de la gestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biens_possedes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien Immobilier',
                'verbose_name_plural': 'Biens Immobiliers',
            },
        ),
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_loyer', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_charges', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('depot_garantie', models.DecimalField(decimal_places=0, max_digits=10)),
                ('jour_paiement', models.PositiveIntegerField(default=5, help_text='Jour du mois limite pour payer (ex: le 5)')),
                ('est_signe', models.BooleanField(default=False)),
                ('fichier_contrat', models.FileField(blank=True, help_text='PDF signé', null=True, upload_to='baux_signes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baux', to=settings.AUTH_USER_MODEL)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baux', to='core.bien')),
            ],
            options={
                'verbose_name': 'Bail / Contrat',
                'verbose_name_plural': 'Baux',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ATTENTE', 'En attente'), ('PUBLIE', 'Publiée'), ('ARCHIVE', 'Archivée')], default='BROUILLON', max_length=10)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annonces', to='core.bien')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_edl', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('date_realisation', models.DateField(default=django.utils.timezone.now)),
                ('checklist', models.TextField(blank=True, help_text="Checklist ou notes détaillées de l'état des lieux.")),
                ('commentaire_general', models.TextField(blank=True)),
                ('signature_bailleur', models.BooleanField(default=False)),
                ('signature_locataire', models.BooleanField(default=False)),
                ('pdf', models.FileField(blank=True, help_text="PDF de l'état des lieux signé.", null=True, upload_to='edl/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to='core.bail')),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'ordering': ['-date_realisation'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu')], default='NOUVEAU', max_length=10)),
                ('photo_avant', models.ImageField(blank=True, null=True, upload_to='interventions/avant/')),
                ('photo_apres', models.ImageField(blank=True, null=True, upload_to='interventions/apres/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interventions_assignees', to=settings.AUTH_USER_MODEL)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='core.bien')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('date_echeance', models.DateField(help_text='Date limite de paiement')),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_verse', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PARTIEL', 'Paiement partiel'), ('PAYE', 'Payé'), ('RETARD', 'En retard')], default='A_PAYER', max_length=10)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('quittance', models.FileField(blank=True, null=True, upload_to='quittances/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyers', to='core.bail')),
            ],
            options={
                'verbose_name': 'Loyer / Échéance',
                'verbose_name_plural': 'Loyers',
            },
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['est_actif', 'created_at'], name='core_bien_est_act_49499e_idx'),
        ),
        migrations.AddIndex(
            model_name='bail',
            index=models.Index(fields=['bien', 'est_signe', 'date_fin'], name='core_bail_bien_id_668928_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loyer',
            unique_together={('bail', 'periode_debut')},
        ),
    ]
