# Generated by Django 5.2.8 on 2025-11-25 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: T3 Centre Ville - Résidence Mada', max_length=200)),
                ('type_bien', models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('MAISON', 'Maison'), ('COMMERCE', 'Local Commercial'), ('TERRAIN', 'Terrain')], default='APPARTEMENT', max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(default='Dakar', max_length=100)),
                ('surface', models.PositiveIntegerField(help_text='En m²')),
                ('nb_pieces', models.PositiveIntegerField(default=1, verbose_name='Nombre de pièces')),
                ('description', models.TextField(blank=True)),
                ('loyer_ref', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Loyer de référence (FCFA/Ar)')),
                ('charges_ref', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Charges estimées')),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='biens/')),
                ('est_actif', models.BooleanField(default=True, help_text='Décocher si le bien est vendu ou retiré de la gestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biens_possedes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien Immobilier',
                'verbose_name_plural': 'Biens Immobiliers',
            },
        ),
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_loyer', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_charges', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('depot_garantie', models.DecimalField(decimal_places=0, max_digits=10)),
                ('jour_paiement', models.PositiveIntegerField(default=5, help_text='Jour du mois limite pour payer (ex: le 5)')),
                ('est_signe', models.BooleanField(default=False)),
                ('fichier_contrat', models.FileField(blank=True, help_text='PDF signé', null=True, upload_to='baux_signes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baux', to=settings.AUTH_USER_MODEL)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baux', to='core.bien')),
            ],
            options={
                'verbose_name': 'Bail / Contrat',
                'verbose_name_plural': 'Baux',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Loyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('date_echeance', models.DateField(help_text='Date limite de paiement')),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_verse', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PARTIEL', 'Paiement partiel'), ('PAYE', 'Payé'), ('RETARD', 'En retard')], default='A_PAYER', max_length=10)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('quittance', models.FileField(blank=True, null=True, upload_to='quittances/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyers', to='core.bail')),
            ],
            options={
                'verbose_name': 'Loyer / Échéance',
                'verbose_name_plural': 'Loyers',
                'unique_together': {('bail', 'periode_debut')},
            },
        ),
    ]
