# Generated by Django 5.2.8 on 2025-11-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bien",
            name="disponible",
            field=models.BooleanField(
                default=True,
                help_text="Disponible immédiatement tant qu'aucun bail actif n'est en cours",
            ),
        ),
    ]
